services:
  db:
    image: mysql:latest
    container_name: task-database
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=task
      - MYSQL_DATABASE=task
      - MYSQL_USER=task
      - MYSQL_PASSWORD=task
